### PR TITLE
Fix running on Windows

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
Also, please - could you add AppVeyor to CI to prevent Windows corruption in future?

**Comment by keradus** [comment]
anyone?

**Comment by keradus** [comment]
?

**Comment by keradus** [comment]
?

**Comment by keradus** [comment]
really ?

**Comment by keradus** [comment]
ping @@klaussilveira

**Comment by keradus** [comment]
boom

**Comment by keradus** [comment]
why this fix was rejected without a word @klaussilveira ?

**Comment by klaussilveira** [comment]
Adding a new platform is a lot of work for a project under maintenance mode. Properly supporting Windows is out of scope of the current library version.

**Pull request closed without merging**
